package hue.captains.singapura.js.homing.workspace.shell;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.log.store.CheckpointWorkerModule;
import hue.captains.singapura.js.homing.workspace.shell.server.WorkspaceServer;

import java.util.List;

/**
 * The addresses the workspace's page reaches for, stamped from Java where they
 * are known, never spelled in its script: the checkpoint worker's module, as
 * the server that serves this page serves it, and where a server that keeps
 * checkpoints takes them.
 *
 * <pre>
 *   const WORKSPACE_ADDRESSES = Object.freeze({ checkpointWorker: "/module?class=…", checkpoints: "/workspace/checkpoints" });
 * </pre>
 */
public record WorkspaceAddressesModule() implements EsModule<WorkspaceAddressesModule>, SelfContent {

    public static final WorkspaceAddressesModule INSTANCE = new WorkspaceAddressesModule();

    public record WORKSPACE_ADDRESSES() implements Exportable._Constant<WorkspaceAddressesModule> {}

    @Override public ImportsFor<WorkspaceAddressesModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<WorkspaceAddressesModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new WORKSPACE_ADDRESSES())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of(
                "// Generated by WorkspaceAddressesModule - do not hand-edit: where the workspace's page reaches.",
                "const WORKSPACE_ADDRESSES = Object.freeze({ checkpointWorker: " + string(resolver.resolve(CheckpointWorkerModule.INSTANCE).basePath())
                        + ", checkpoints: " + string(WorkspaceServer.CHECKPOINTS) + " });");
    }

    /** A JavaScript string of an address: the few marks an address is made of, quoted. */
    private static String string(String address) {
        if (!address.matches("[A-Za-z0-9/?=&._%-]*")) throw new IllegalArgumentException("not a plain address: " + address);
        return "\"" + address + "\"";
    }
}
