package hue.captains.singapura.js.homing.workspace.codecs;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Build-time entry point: walk the workspace's codec manifest and emit
 * one ES-module JS file containing every typed class declaration plus
 * its matching codec.
 *
 * <p>Invoked by the Maven {@code exec} plugin during the
 * {@code process-classes} phase. Writes a single file —
 * {@code WorkspaceStateCodecs.js} — into the resources output directory
 * passed as the sole argument. The framework's classpath-resource serving
 * picks it up at request time the same way it would a hand-written
 * resource — except this one is regenerated on every build.</p>
 *
 * <h2>Per-entry codegen dispatch</h2>
 *
 * <p>Each manifest entry carries its own {@code DefinitionCodeGen} and
 * {@code FunctionsCodeGen} pair. The umbrella generator doesn't pick a
 * single codegen for the whole manifest — each entry decides whether to
 * use the existing hand-written codegens (for sealed sums, recursive
 * records, validation-heavy wrappers) or the reflective Ecma defaults
 * (for the simple-record shapes the slim-Jackson path covers losslessly).
 * Both implementation strategies conform to the same {@code FunctionalObject}
 * contract; the consumer reads one stream of generated JS.</p>
 *
 * <h2>"CodeGen as Functions" — same code path at build and runtime</h2>
 *
 * <p>The body of this {@code main} is a pure traversal of
 * {@link WorkspaceStateCodecsManifest#ENTRIES}. The same composition
 * could be invoked at runtime (from a {@code DomModule}'s
 * {@code selfContent}) if a downstream consumer wanted runtime
 * generation — no change to the codegens themselves. Build-time is the
 * default because it surfaces errors earlier, has zero per-request cost,
 * and the output is inspectable on disk for debugging.</p>
 *
 * @since RFC 0034 P2-prep — codec generation foundation
 */
public final class WorkspaceCodecGen {

    private WorkspaceCodecGen() {}

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException(
                    "Usage: WorkspaceCodecGen <output-directory>");
        }
        Path outDir = Paths.get(args[0]);
        Files.createDirectories(outDir);

        String body = generate();
        // Filename MUST match the Java DomModule's SimpleName so the
        // framework's ModuleNameResolver finds it at the expected
        // classpath URL when chrome bodyImports() resolves the import.
        Path outFile = outDir.resolve("WorkspaceStateCodecsModule.js");
        Files.writeString(outFile, body, StandardCharsets.UTF_8);

        System.out.println("[WorkspaceCodecGen] wrote " + outFile
                + " (" + body.length() + " chars, "
                + WorkspaceStateCodecsManifest.ENTRIES.size()
                + " entries)");
    }

    /**
     * Pure-function form of the generator: returns the full ES-module
     * body as a string. Each entry's codegens decide their own output;
     * the umbrella concatenates with blank-line separators. Exposed for
     * parity testing (compare against the existing hand-written bundle
     * byte-for-byte) and for any future runtime invocation.
     */
    public static String generate() {
        var sb = new StringBuilder();
        sb.append("// =============================================================================\n");
        sb.append("// Generated by WorkspaceCodecGen — do not edit by hand.\n");
        sb.append("// Source-of-truth: hue.captains.singapura.js.homing.workspace.codecs.\n");
        sb.append("//                  WorkspaceStateCodecsManifest\n");
        sb.append("// =============================================================================\n");
        sb.append("\n");
        for (CodecEntry<?> entry : WorkspaceStateCodecsManifest.ENTRIES) {
            emit(sb, entry);
        }
        return sb.toString();
    }

    /**
     * Emit one entry: its class definition, a blank line, then its codec
     * functions. Each codegen is type-locked to its own entry — they
     * verify the {@code ObjectDefinition} matches the type they handle
     * and throw if anything else is passed. Defensive at the call site;
     * the umbrella just routes.
     */
    private static <T> void emit(StringBuilder sb, CodecEntry<T> entry) {
        var def = entry.definition();
        sb.append(entry.defGen().generate(def));
        sb.append('\n');
        sb.append(entry.fnGen().generate(def));
        sb.append('\n');
    }
}
