package hue.captains.singapura.js.homing.workspace.codecs;

import hue.captains.singapura.js.homing.codec.ObjectDefinition;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Manifest + umbrella generator structural tests.
 *
 * <p>Three properties enforced here:</p>
 *
 * <ol>
 *   <li><b>Every entry produces non-empty output.</b> A silent codegen
 *       (returning {@code ""}) would slip past type checks but break the
 *       module. Each entry must contribute at least one top-level
 *       declaration.</li>
 *   <li><b>Every entry's typed class and codec name appear in the
 *       output.</b> Catches the wiring mistake where an entry references
 *       a codegen that emits a different name than the Java module's
 *       {@code exports()} declares.</li>
 *   <li><b>Manifest-driven output equals direct codegen invocation.</b>
 *       {@link WorkspaceCodecGen#generate()} is the build-time entry
 *       point; this test verifies it's a pure function of the manifest
 *       (no hidden ordering, no extra concatenation) by replaying the
 *       same codegens directly and asserting byte equality.</li>
 * </ol>
 */
class WorkspaceCodecGenTest {

    /**
     * Every Java type in the manifest has a matching declaration in the
     * generated module body. Catches the case where someone adds an entry
     * to the manifest but the codegen wasn't actually run or emitted the
     * wrong class name.
     */
    @Test
    void everyManifestEntryAppearsInGeneratedOutput() {
        String body = WorkspaceCodecGen.generate();
        for (CodecEntry<?> entry : WorkspaceStateCodecsManifest.ENTRIES) {
            String typeName = entry.type().getSimpleName();
            assertTrue(body.contains(typeName),
                    "Generated body missing declaration for: " + typeName);
            assertTrue(body.contains(typeName + "Codec"),
                    "Generated body missing codec for: " + typeName);
        }
    }

    /**
     * The header banner naming the manifest as source-of-truth is the
     * doctrine breadcrumb — a human opening the generated file must see
     * the words "do not edit by hand" and the manifest's FQCN. Drop this
     * accidentally and the file becomes hand-editable by inattention.
     */
    @Test
    void generatedHeaderNamesTheManifest() {
        String body = WorkspaceCodecGen.generate();
        assertTrue(body.contains("Generated by WorkspaceCodecGen"),
                "Header missing generator name");
        assertTrue(body.contains("do not edit by hand"),
                "Header missing edit-warning");
        assertTrue(body.contains("WorkspaceStateCodecsManifest"),
                "Header missing source-of-truth FQCN");
    }

    /**
     * Manifest size matches expectation. Acts as a tripwire — any
     * intentional addition to the manifest must update this constant,
     * forcing the reviewer to consider the export-list update too.
     */
    @Test
    void manifestEntryCountMatchesExpectation() {
        assertEquals(14, WorkspaceStateCodecsManifest.ENTRIES.size(),
                "Manifest size changed without test update — confirm "
              + "WorkspaceStateCodecsModule.exports() is also updated.");
    }

    /**
     * Per-entry codegens are pure functions. Invoking them directly
     * produces the same body the umbrella generator does. Test catches
     * non-determinism (hashmap iteration, time-stamped output, etc.).
     */
    @Test
    void umbrellaGeneratorIsPureFunctionOfManifest() {
        String first  = WorkspaceCodecGen.generate();
        String second = WorkspaceCodecGen.generate();
        assertEquals(first, second,
                "Umbrella generator is not deterministic — runs differ.");
    }

    /**
     * Smoke check: each manifest entry's codegens are type-locked to the
     * entry's type. Asking a hand-written codegen for the wrong type
     * throws — that's a build-time contract test for the codegen
     * implementations.
     */
    @Test
    void everyManifestEntryProducesNonEmptyDefinitionAndCodec() {
        for (CodecEntry<?> entry : WorkspaceStateCodecsManifest.ENTRIES) {
            ObjectDefinition<?> def = entry.definition();
            String defSrc = entry.defGen().generate(def);
            String fnSrc  = entry.fnGen().generate(def);
            assertTrue(defSrc != null && !defSrc.isBlank(),
                    "Definition codegen returned empty for: " + entry.type().getSimpleName());
            assertTrue(fnSrc != null && !fnSrc.isBlank(),
                    "Functions codegen returned empty for: " + entry.type().getSimpleName());
        }
    }

    /**
     * Manifest covers exactly the 14 currently-supported workspace types.
     * Adding a new entry should also update this list — keeps the
     * manifest and tests in lock-step.
     */
    @Test
    void manifestCoversExpectedTypeSet() {
        List<String> expected = List.of(
                "PaneId", "WidgetInstanceId", "WidgetKind", "WorkspaceKind",
                "WidgetTitle", "ThemeName",
                "WorkspaceName", "WorkspaceInstanceId",
                "Orientation", "WidgetLocation",
                "LayoutNode", "ChromeState",
                "WidgetInstance", "WorkspaceState"
        );
        List<String> actual = WorkspaceStateCodecsManifest.ENTRIES.stream()
                .map(e -> e.type().getSimpleName())
                .toList();
        assertEquals(expected, actual,
                "Manifest types or ordering changed — update test expectation.");
    }
}
