package hue.captains.singapura.js.homing.workspace.stage;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The stage party's type, as the page has it: {@code STAGE}, generated from {@link StageParty#TYPE}. */
public record StagePartyModule() implements EsModule<StagePartyModule>, SelfContent {

    public static final StagePartyModule INSTANCE = new StagePartyModule();

    public record STAGE() implements Exportable._Constant<StagePartyModule> {}

    @Override public ImportsFor<StagePartyModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<StagePartyModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new STAGE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by StagePartyModule from StageParty.TYPE - do not hand-edit.", StageParty.TYPE.js());
    }
}
