package hue.captains.singapura.js.homing.workspace.core;

import hue.captains.singapura.js.homing.workspace.core.models.WidgetId;
import hue.captains.singapura.js.homing.workspace.core.models.WidgetName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;

/**
 * The workspace's headless core (RFC 0066 E3, the workspace detour): the
 * ROSTER - the widgets the workspace holds, each under an id of its own that
 * says what it is ({@link WidgetIds}) - and their LIFE, which is their panes'
 * too: a widget and its pane live and die together. A widget is created - its
 * pane lent by the register of panes, placed nowhere, the widget made in it,
 * and said opened - and closed - said closing, disposed, its pane closed, said
 * closed.
 *
 * <p>What a user asks is a REQUEST, and the core executes it, handled by the
 * core and the placement in an order fixed for its type: an {@link
 * Request.Open} is create, then mount at the location it names - a mount that
 * fails closes what was created; a {@link Request.Close} is unmount, then
 * close; a {@link Request.Rename} is the roster's and the pane's alone - the name
 * kept, the pane titled again directly by the register. The placement mounts
 * and unmounts, and never creates, closes or renames; the
 * core calls it only in executing a request. A restore creates without
 * mounting ({@link #create}), and each placement mounts from its own state.</p>
 *
 * <p>The JavaScript is this, step for step (WorkspaceCoreModule.js); the two
 * agree on the ids and on what they say (WorkspaceCoreParityTest). What else a
 * widget's opening means - its DomOps root grafted, its messaging parties
 * joined - is a listener's, never the core's.</p>
 *
 * @param <C> a container, as the register of panes lends it
 * @param <W> a widget
 * @param <L> a location, as the placement names one
 */
public final class WorkspaceCore<C, W, L> {

    /** A kind of widget: how one is made in a container, with its params, and disposed. */
    public interface Kind<C, W> {
        W make(C container, Map<String, String> params);
        void dispose(W widget);
    }

    /**
     * The register of panes: lends a widget its pane, placed nowhere, titled after
     * the widget; titles it again when the widget is renamed; and closes it with
     * the widget.
     */
    public interface Panes<C> {
        C lend(Entry<?> entry);
        void rename(Entry<?> entry);
        void release(Entry<?> entry);
    }

    /** Where panes are shown: a widget's mounted at a location, and unmounted - never created, never closed here. */
    public interface Placement<L> {
        void mount(Entry<?> entry, L location);
        void unmount(Entry<?> entry);
    }

    /**
     * A widget the workspace holds: its id, its kind, its params, the name a user
     * gave it if any - titled by its identity until then - and the widget, null
     * while it is being made.
     */
    public record Entry<W>(WidgetId id, String kind, Map<String, String> params, Optional<WidgetName> name, W widget) {
        public Entry { params = Map.copyOf(params); Objects.requireNonNull(name, "Entry.name"); }
    }

    /** What a user asks - generated by a control, executed by the core. */
    public sealed interface Request<L> {
        /** A widget of a kind, with its params, opened and mounted at the location named. */
        record Open<L>(String kind, Map<String, String> params, L location) implements Request<L> {
            public Open {
                Objects.requireNonNull(kind, "Open.kind");
                params = params == null ? Map.of() : Map.copyOf(params);
            }
        }
        /** A widget named by a user - or its name taken back, none: recorded, and its pane titled again. */
        record Rename<L>(WidgetId id, Optional<WidgetName> name) implements Request<L> {
            public Rename {
                Objects.requireNonNull(id, "Rename.id");
                Objects.requireNonNull(name, "Rename.name");
            }
        }
        /** A widget unmounted and closed. */
        record Close<L>(WidgetId id) implements Request<L> {
            public Close { Objects.requireNonNull(id, "Close.id"); }
        }
    }

    /** What the core says, in the order it happens. */
    public sealed interface Notice {
        /** A widget was made, and is in the roster. */
        record WidgetOpened(Entry<?> entry) implements Notice {}
        /** A widget was named, or its name taken back: the roster holds the entry as it is now. */
        record WidgetRenamed(Entry<?> entry) implements Notice {}
        /** A widget is about to be disposed: still whole, still in the roster. */
        record WidgetClosing(Entry<?> entry) implements Notice {}
        /** A widget is gone: disposed, its pane closed, out of the roster. */
        record WidgetClosed(WidgetId id, String kind) implements Notice {}
    }

    private final Map<String, Kind<C, W>> kinds;
    private final Panes<C> panes;
    private final Placement<L> placement;
    private final Map<WidgetId, Entry<W>> roster = new LinkedHashMap<>();
    private final Map<String, Integer> sequences = new HashMap<>();
    private final List<Consumer<Notice>> listeners = new CopyOnWriteArrayList<>();

    public WorkspaceCore(Map<String, Kind<C, W>> kinds, Panes<C> panes, Placement<L> placement) {
        this.kinds = Map.copyOf(Objects.requireNonNull(kinds, "WorkspaceCore.kinds"));
        this.panes = Objects.requireNonNull(panes, "WorkspaceCore.panes");
        this.placement = Objects.requireNonNull(placement, "WorkspaceCore.placement");
    }

    /**
     * A request executed, in its type's order: an open - created, then mounted, or
     * closed again when the mount fails - gives the entry; a close - unmounted, then
     * closed - gives nothing; a rename - recorded, then the widget's pane titled
     * again by the register, the placement asked nothing - gives the entry as it is now.
     */
    public Optional<Entry<W>> execute(Request<L> request) {
        return switch (request) {
            case Request.Open<L> o -> {
                var entry = create(o.kind(), o.params(), null);
                try { placement.mount(entry, o.location()); }
                catch (RuntimeException e) { close(entry); throw e; }
                yield Optional.of(entry);
            }
            case Request.Rename<L> r -> {
                var was = held(r.id());
                var named = new Entry<>(was.id(), was.kind(), was.params(), r.name(), was.widget());
                roster.put(named.id(), named);
                say(new Notice.WidgetRenamed(named));
                panes.rename(named);
                yield Optional.of(named);
            }
            case Request.Close<L> c -> {
                var entry = held(c.id());
                placement.unmount(entry);
                close(entry);
                yield Optional.empty();
            }
        };
    }

    /**
     * A widget of a kind created, placed nowhere - under the id given, when one is
     * (a widget coming back), else the next of its prefix. An id given must be one
     * its kind and params would make, and not held already; the sequence goes on
     * past it. A restore's step; what a user asks goes through {@link #execute}.
     */
    public Entry<W> create(String kind, Map<String, String> params, WidgetId id) { return create(kind, params, id, Optional.empty()); }

    /** The same, a widget coming back under the name a user gave it. */
    public Entry<W> create(String kind, Map<String, String> params, WidgetId id, Optional<WidgetName> name) {
        var k = kinds.get(kind);
        if (k == null) throw new IllegalArgumentException("[WorkspaceCore] no kind '" + kind + "': " + String.join(", ", new java.util.TreeSet<>(kinds.keySet())));
        var p = params == null ? Map.<String, String>of() : params;
        String prefix = WidgetIds.prefix(kind, p);
        WidgetId wid = id == null ? WidgetIds.of(prefix, sequences.getOrDefault(prefix, 0) + 1) : given(id, prefix);
        sequences.merge(prefix, wid.sequence(), Math::max);
        var lent = new Entry<W>(wid, kind, p, Objects.requireNonNull(name, "name"), null);
        C container = panes.lend(lent);
        W widget;
        try { widget = k.make(container, p); }
        catch (RuntimeException e) { panes.release(lent); throw e; }   // the id is spent: never reused
        var entry = new Entry<>(wid, kind, p, name, widget);
        roster.put(wid, entry);
        say(new Notice.WidgetOpened(entry));
        return entry;
    }

    /**
     * The ids of a prefix spent up to the sequence given, whether the widgets are
     * held or not - a workspace coming back, which gave them before: the next of
     * the prefix is past it. Never back.
     */
    public void spend(String prefix, int last) {
        if (last < 1) throw new IllegalArgumentException("[WorkspaceCore] a sequence starts at 1: " + last);
        sequences.merge(Objects.requireNonNull(prefix, "prefix"), last, Math::max);
    }

    private WidgetId given(WidgetId id, String prefix) {
        if (roster.containsKey(id)) throw new IllegalArgumentException("[WorkspaceCore] '" + id + "' is held already");
        if (!id.prefix().equals(prefix)) throw new IllegalArgumentException("[WorkspaceCore] '" + id + "' is not what its kind and params make: " + prefix + "-n");
        return id;
    }

    private Entry<W> held(WidgetId id) {
        var entry = roster.get(id);
        if (entry == null) throw new IllegalArgumentException("[WorkspaceCore] no widget '" + id + "'");
        return entry;
    }

    /** A widget closed: said closing, disposed, its pane closed, said closed. */
    private void close(Entry<W> entry) {
        say(new Notice.WidgetClosing(entry));
        try { kinds.get(entry.kind()).dispose(entry.widget()); }
        finally {
            roster.remove(entry.id());
            panes.release(entry);
            say(new Notice.WidgetClosed(entry.id(), entry.kind()));
        }
    }

    /**
     * The workspace taken down: every widget closed, the last opened first, with no
     * placement asked - not what a user asked, and nothing of it to keep.
     */
    public void dispose() {
        var all = new ArrayList<>(roster.values());
        for (int i = all.size() - 1; i >= 0; i--) close(all.get(i));
    }

    public Optional<Entry<W>> entry(WidgetId id) { return Optional.ofNullable(roster.get(id)); }

    /** The roster, in the order its widgets were opened. */
    public List<Entry<W>> entries() { return List.copyOf(new ArrayList<>(roster.values())); }

    /** A listener, told every notice; the runnable returned takes it off. */
    public Runnable on(Consumer<Notice> listener) {
        listeners.add(Objects.requireNonNull(listener));
        return () -> listeners.remove(listener);
    }

    private void say(Notice n) { for (var l : listeners) l.accept(n); }
}
