package hue.captains.singapura.js.homing.workspace.core;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;

import java.util.List;

/**
 * What a user asks of the workspace, as data, in JavaScript - the dual of
 * {@link hue.captains.singapura.js.homing.workspace.core.WorkspaceCore.Request}: generated by a control,
 * executed by the core. It touches no DOM.
 */
public record WorkspaceRequestModule() implements EsModule<WorkspaceRequestModule> {

    public record WorkspaceRequest() implements Exportable._Class<WorkspaceRequestModule> {}

    public static final WorkspaceRequestModule INSTANCE = new WorkspaceRequestModule();

    @Override
    public ImportsFor<WorkspaceRequestModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<WorkspaceRequestModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new WorkspaceRequest())); }
}
