package hue.captains.singapura.js.homing.workspace.codecs.log;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.RecordComponent;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * What the generators read off a type at build time, said once: its
 * components and their slots, the sealed type it is a variant of, the grammar
 * it declares. Build-time reflection only — what it reads becomes source code,
 * and nothing reads a class at run time.
 */
final class LogShapes {

    private LogShapes() {}

    /** The Java package the generated Java codecs are written into. */
    static final String JAVA_PACKAGE = "hue.captains.singapura.js.homing.workspace.log.codec";

    /** A record component: its name, and what it is on the wire. */
    record Component(String name, LogSlot slot) {}

    static List<Component> components(Class<?> type) {
        if (!type.isRecord()) throw new IllegalArgumentException(type.getName() + " is not a record");
        var out = new ArrayList<Component>();
        for (RecordComponent rc : type.getRecordComponents()) {
            out.add(new Component(rc.getName(), LogSlot.of(rc.getGenericType(), type.getSimpleName() + "." + rc.getName())));
        }
        return out;
    }

    /** The sealed interface this record is a variant of, or null. */
    static Class<?> sealedParent(Class<?> type) {
        for (Class<?> i : type.getInterfaces()) if (i.isSealed()) return i;
        return null;
    }

    /** The regular expression the type's {@code GRAMMAR} holds, or null when it declares none. */
    static String grammar(Class<?> type) {
        Field f;
        try { f = type.getDeclaredField("GRAMMAR"); }
        catch (NoSuchFieldException e) { return null; }
        if (!Modifier.isStatic(f.getModifiers()) || f.getType() != Pattern.class) return null;
        try {
            f.setAccessible(true);
            String src = ((Pattern) f.get(null)).pattern();
            if (!SAFE_GRAMMAR.matcher(src).matches()) {
                throw new IllegalArgumentException(type.getName() + ".GRAMMAR \"" + src
                        + "\" uses syntax that may read differently in JavaScript; keep to classes, groups, ?, *, +, | and \\d");
            }
            return src;
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("cannot read " + type.getName() + ".GRAMMAR", e);
        }
    }

    /** Pattern syntax Java and JavaScript read alike: literals, classes, groups, quantifiers, alternation, \d. */
    private static final Pattern SAFE_GRAMMAR = Pattern.compile("(?:[A-Za-z0-9_\\-\\[\\]()?*+|/ ]|\\\\d)*");

    /**
     * The type's public constants a JavaScript reader needs as much as a Java one
     * — public static final strings, ints, longs and booleans, a long only when
     * it is a safe integer — as {@code static NAME = literal;} lines, in the order
     * declared. Anything else a type keeps static is Java's alone.
     */
    static String jsConstants(Class<?> type) {
        var sb = new StringBuilder();
        for (Field f : type.getDeclaredFields()) {
            int m = f.getModifiers();
            if (!Modifier.isPublic(m) || !Modifier.isStatic(m) || !Modifier.isFinal(m)) continue;
            Object v;
            try { v = f.get(null); }
            catch (IllegalAccessException e) { throw new IllegalStateException("cannot read " + type.getName() + "." + f.getName(), e); }
            String literal;
            if (f.getType() == String.class) literal = LogSlot.javaString((String) v);
            else if (f.getType() == int.class || f.getType() == boolean.class) literal = String.valueOf(v);
            else if (f.getType() == long.class && Math.abs((Long) v) <= 9_007_199_254_740_991L) literal = String.valueOf(v);
            else continue;
            sb.append("    static ").append(f.getName()).append(" = ").append(literal).append(";\n");
        }
        return sb.toString();
    }

    static String simple(Class<?> t) { return t.getSimpleName(); }

    static String codec(Class<?> t) { return t.getSimpleName() + "Codec"; }

    /** The head of a generated Java codec: package, imports, the class line. */
    static String javaHead(Class<?> t, String valueType) {
        return "package " + JAVA_PACKAGE + ";\n\n"
             + "import hue.captains.singapura.js.homing.codec.TransformationFunctions;\n"
             + "import hue.captains.singapura.js.homing.workspace.log.json.Json;\n"
             + "import hue.captains.singapura.js.homing.workspace.log.json.Wire;\n\n"
             + "/** Generated by WorkspaceLogJavaGen from {@code " + t.getCanonicalName() + "} — do not edit. */\n"
             + "public final class " + codec(t) + " implements TransformationFunctions<" + valueType + ", Json> {\n\n"
             + "    public static final " + codec(t) + " INSTANCE = new " + codec(t) + "();\n\n"
             + "    private " + codec(t) + "() {}\n\n";
    }
}
