package hue.captains.singapura.js.homing.workspace.codecs.log;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Build-time entry point: the workspace log's JavaScript — every manifest
 * type's class, then every one's codec — written as one ES module body,
 * {@code WorkspaceLogCodecsModule.js}, into the directory given, where the
 * framework serves it as {@code WorkspaceLogCodecsModule}. Run by the exec
 * plugin at process-classes; the output lives under {@code target/} only.
 */
public final class WorkspaceLogJsGen {

    private WorkspaceLogJsGen() {}

    public static final String OUTPUT_FILE = "WorkspaceLogCodecsModule.js";

    public static void main(String[] args) throws IOException {
        if (args.length != 1) throw new IllegalArgumentException("Usage: WorkspaceLogJsGen <output-directory>");
        Path out = Path.of(args[0]);
        Files.createDirectories(out);
        Files.writeString(out.resolve(OUTPUT_FILE), generate(), StandardCharsets.UTF_8);
        System.out.println("[WorkspaceLogJsGen] wrote " + OUTPUT_FILE + " (" + WorkspaceLogManifest.ENTRIES.size() + " types)");
    }

    /** The names the module exports: each type's class and its codec, in the manifest's order. */
    public static List<String> exportedNames() {
        var out = new ArrayList<String>();
        for (var e : WorkspaceLogManifest.ENTRIES) {
            out.add(e.type().getSimpleName());
            out.add(e.type().getSimpleName() + "Codec");
        }
        return out;
    }

    public static String generate() {
        WorkspaceLogManifest.check(WorkspaceLogManifest.ENTRIES);
        var sb = new StringBuilder();
        sb.append("// =============================================================================\n");
        sb.append("// Generated by WorkspaceLogJsGen from WorkspaceLogManifest — do not edit by hand.\n");
        sb.append("// The workspace log's types, declared in Java: each a frozen class that checks\n");
        sb.append("// what it is given, and a codec to and from the wire — strings, safe integers,\n");
        sb.append("// booleans, arrays and objects, nothing ambiguous.\n");
        sb.append("// =============================================================================\n\n");
        sb.append(PRELUDE).append('\n');
        for (var e : WorkspaceLogManifest.ENTRIES) sb.append(e.jsDefinition().generate(e.definition())).append('\n');
        for (var e : WorkspaceLogManifest.ENTRIES) sb.append(e.jsFunctions().generate(e.definition())).append('\n');
        return sb.toString();
    }

    /** What every generated class and codec leans on: a refusal that says where, and the wire's shapes read. */
    private static final String PRELUDE = """
            /** The wire's shapes, read; a refusal names the field that refused. Not exported. */
            class LogWire {
                static UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

                static show(v) {
                    try { const s = JSON.stringify(v); return s === undefined ? String(v) : s; }
                    catch (e) { return String(v); }
                }

                static no(what, why) { throw new TypeError(what + ": " + why); }

                static object(w, what, keys) {
                    if (w === null || typeof w !== "object" || Array.isArray(w)) LogWire.no(what, "expected an object, got " + LogWire.show(w));
                    for (const k of Object.keys(w)) if (!keys.includes(k)) LogWire.no(what, "no member " + LogWire.show(k));
                    for (const k of keys) if (!Object.prototype.hasOwnProperty.call(w, k)) LogWire.no(what, "the member " + LogWire.show(k) + " is missing");
                    return w;
                }

                static type(w, what) {
                    if (w === null || typeof w !== "object" || typeof w.type !== "string") LogWire.no(what, "expected an object that says its type, got " + LogWire.show(w));
                    return w.type;
                }

                static array(w, what) {
                    if (!Array.isArray(w)) LogWire.no(what, "expected an array, got " + LogWire.show(w));
                    return w;
                }
            }
            """;
}
