package hue.captains.singapura.js.homing.workspace.codecs.log;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Build-time entry point: the workspace log's JavaScript — a module per
 * top-level Java declaration ({@link LogModules}), each type's class then each
 * one's codec, and the wire's reader in a module of its own — with the Java
 * that serves each: its {@code DomModule}, naming what it exports and imports,
 * and the crate of them all. Run by the exec plugin of the output-only module
 * that serves them, at generate-sources: the JavaScript under its classes
 * directory, the Java under its generated source root. Nothing of it lives in
 * {@code src/}.
 */
public final class WorkspaceLogJsGen {

    private WorkspaceLogJsGen() {}

    /** The crate the modules are served in: the output-only module's own. */
    public static final String CRATE = "WorkspaceLogCodecCrate";
    public static final String CRATE_NAME = "homing-workspace-log-codec";

    public static void main(String[] args) throws IOException {
        if (args.length != 2) throw new IllegalArgumentException("Usage: WorkspaceLogJsGen <classes-directory> <java-source-directory>");
        String pkg = LogModules.PACKAGE.replace('.', '/');
        Path js = Path.of(args[0]).resolve("homing/js").resolve(pkg), java = Path.of(args[1]).resolve(pkg);
        Files.createDirectories(js);
        Files.createDirectories(java);
        var scripts = scripts();
        for (var s : scripts.entrySet()) Files.writeString(js.resolve(s.getKey()), s.getValue(), StandardCharsets.UTF_8);
        var sources = javaSources();
        for (var s : sources.entrySet()) Files.writeString(java.resolve(s.getKey()), s.getValue(), StandardCharsets.UTF_8);
        System.out.println("[WorkspaceLogJsGen] wrote " + scripts.size() + " modules to " + js + " and their Java to " + java);
    }

    /** The modules, in import order. */
    public static List<LogModules.Module> modules() {
        WorkspaceLogManifest.check(WorkspaceLogManifest.ENTRIES);
        return LogModules.of(WorkspaceLogManifest.ENTRIES);
    }

    /** File name to script body, the wire's reader's first, then each module after all it imports. */
    public static Map<String, String> scripts() {
        var out = new LinkedHashMap<String, String>();
        out.put(LogModules.WIRE_MODULE + ".js", head("the wire's reader: the refusals every class and codec makes, and the wire's shapes read") + WIRE);
        for (var m : modules()) out.put(m.name() + ".js", script(m));
        return out;
    }

    static String script(LogModules.Module m) {
        var sb = new StringBuilder(head("generated from " + m.top().getName() + ": each type declared there, a class and a codec"));
        for (var e : m.entries()) sb.append(e.jsDefinition().generate(e.definition())).append('\n');
        for (var e : m.entries()) sb.append(e.jsFunctions().generate(e.definition())).append('\n');
        return sb.toString();
    }

    private static String head(String what) {
        return "// =============================================================================\n"
             + "// Generated by WorkspaceLogJsGen from WorkspaceLogManifest — do not edit by hand.\n"
             + "// The workspace log's types, declared in Java: " + what + ".\n"
             + "// =============================================================================\n\n";
    }

    /** File name to Java source: each module's DomModule, then the crate. */
    public static Map<String, String> javaSources() {
        var out = new LinkedHashMap<String, String>();
        out.put(LogModules.WIRE_MODULE + ".java", domModule(LogModules.WIRE_MODULE, "the wire's reader, which every other module imports",
                List.of(LogModules.WIRE), Map.of()));
        var names = new ArrayList<String>();
        names.add(LogModules.WIRE_MODULE);
        for (var m : modules()) {
            out.put(m.name() + ".java", domModule(m.name(), "{@code " + m.top().getName() + "}", m.exports(), m.imports()));
            names.add(m.name());
        }
        out.put(CRATE + ".java", crate(names));
        return out;
    }

    private static String domModule(String name, String from, List<String> exports, Map<String, List<String>> imports) {
        var sb = new StringBuilder();
        sb.append("package ").append(LogModules.PACKAGE).append(";\n\n");
        sb.append("import hue.captains.singapura.js.homing.core.DomModule;\n");
        sb.append("import hue.captains.singapura.js.homing.core.Exportable;\n");
        sb.append("import hue.captains.singapura.js.homing.core.ExportsOf;\n");
        sb.append("import hue.captains.singapura.js.homing.core.ImportsFor;\n");
        sb.append("import hue.captains.singapura.js.homing.core.ModuleImports;\n\n");
        sb.append("import java.util.List;\n\n");
        sb.append("/** Generated by WorkspaceLogJsGen from ").append(from).append(" — do not edit. */\n");
        sb.append("public record ").append(name).append("() implements DomModule<").append(name).append("> {\n\n");
        sb.append("    public static final ").append(name).append(" INSTANCE = new ").append(name).append("();\n\n");
        for (String x : exports) {
            sb.append("    public record ").append(x).append("() implements Exportable._Class<").append(name).append("> {}\n");
        }
        sb.append("\n    @Override\n");
        sb.append("    public ImportsFor<").append(name).append("> imports() {\n");
        if (name.equals(LogModules.WIRE_MODULE)) {
            sb.append("        return ImportsFor.noImports();\n");
        } else {
            sb.append("        return ImportsFor.<").append(name).append(">builder()\n");
            sb.append(importLine(LogModules.WIRE_MODULE, List.of(LogModules.WIRE)));
            for (var i : imports.entrySet()) sb.append(importLine(i.getKey(), i.getValue()));
            sb.append("                .build();\n");
        }
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public ExportsOf<").append(name).append("> exports() {\n");
        sb.append("        return new ExportsOf<>(INSTANCE, List.of(");
        for (int i = 0; i < exports.size(); i++) sb.append(i > 0 ? ", " : "").append("new ").append(exports.get(i)).append("()");
        sb.append("));\n    }\n}\n");
        return sb.toString();
    }

    private static String importLine(String module, List<String> names) {
        var sb = new StringBuilder("                .add(new ModuleImports<>(List.of(");
        for (int i = 0; i < names.size(); i++) sb.append(i > 0 ? ", " : "").append("new ").append(module).append('.').append(names.get(i)).append("()");
        return sb.append("), ").append(module).append(".INSTANCE))\n").toString();
    }

    private static String crate(List<String> modules) {
        var sb = new StringBuilder();
        sb.append("package ").append(LogModules.PACKAGE).append(";\n\n");
        sb.append("import hue.captains.singapura.js.homing.core.Crate;\n");
        sb.append("import hue.captains.singapura.js.homing.core.CrateEntry;\n");
        sb.append("import hue.captains.singapura.js.homing.core.StandardJsModuleType;\n\n");
        sb.append("import java.util.List;\n\n");
        sb.append("/**\n");
        sb.append(" * Generated by WorkspaceLogJsGen — do not edit. The workspace log's types in\n");
        sb.append(" * JavaScript: a module per top-level Java declaration, and the wire's reader,\n");
        sb.append(" * each listed after every module it imports. They import nothing outside.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(CRATE).append(" implements Crate {\n\n");
        sb.append("    public static final ").append(CRATE).append(" INSTANCE = new ").append(CRATE).append("();\n\n");
        sb.append("    private ").append(CRATE).append("() {}\n\n");
        sb.append("    @Override public String name() { return \"").append(CRATE_NAME).append("\"; }\n\n");
        sb.append("    @Override public List<Crate> requires() { return List.of(); }\n\n");
        sb.append("    @Override\n");
        sb.append("    public List<CrateEntry> entries() {\n");
        sb.append("        return List.of(\n");
        for (int i = 0; i < modules.size(); i++) {
            sb.append("                CrateEntry.of(").append(modules.get(i)).append(".INSTANCE, StandardJsModuleType.PURE_LOGIC)")
              .append(i < modules.size() - 1 ? ",\n" : ");\n");
        }
        sb.append("    }\n\n");
        sb.append("    /** Each module's served script, after every one it imports: an order one scope can evaluate them in. */\n");
        sb.append("    public static List<String> scripts() {\n");
        sb.append("        return INSTANCE.entries().stream().map(e -> \"/homing/js/\" + e.moduleClass().replace('.', '/') + \".js\").toList();\n");
        sb.append("    }\n}\n");
        return sb.toString();
    }

    /** The wire's reader: a refusal that says where, and the wire's shapes read. */
    private static final String WIRE = """
            /** The wire's shapes, read; a refusal names the field that refused. */
            class LogWire {
                static UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

                static show(v) {
                    try { const s = JSON.stringify(v); return s === undefined ? String(v) : s; }
                    catch (e) { return String(v); }
                }

                static no(what, why) { throw new TypeError(what + ": " + why); }

                static object(w, what, keys) {
                    if (w === null || typeof w !== "object" || Array.isArray(w)) LogWire.no(what, "expected an object, got " + LogWire.show(w));
                    for (const k of Object.keys(w)) if (!keys.includes(k)) LogWire.no(what, "no member " + LogWire.show(k));
                    for (const k of keys) if (!Object.prototype.hasOwnProperty.call(w, k)) LogWire.no(what, "the member " + LogWire.show(k) + " is missing");
                    return w;
                }

                static type(w, what) {
                    if (w === null || typeof w !== "object" || typeof w.type !== "string") LogWire.no(what, "expected an object that says its type, got " + LogWire.show(w));
                    return w.type;
                }

                static array(w, what) {
                    if (!Array.isArray(w)) LogWire.no(what, "expected an array, got " + LogWire.show(w));
                    return w;
                }
            }
            """;
}
