package hue.captains.singapura.js.homing.workspace.groups;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The workspace choice party's type, as the page has it: {@code WORKSPACE_CHOICE},
 * generated from {@link WorkspaceChoice#TYPE} - its name, and each kind's fields
 * with their types - so every message is checked against what Java declared.
 */
public record WorkspaceChoiceModule() implements EsModule<WorkspaceChoiceModule>, SelfContent {

    public static final WorkspaceChoiceModule INSTANCE = new WorkspaceChoiceModule();

    public record WORKSPACE_CHOICE() implements Exportable._Constant<WorkspaceChoiceModule> {}

    @Override public ImportsFor<WorkspaceChoiceModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<WorkspaceChoiceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new WORKSPACE_CHOICE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by WorkspaceChoiceModule from WorkspaceChoice.TYPE - do not hand-edit.", WorkspaceChoice.TYPE.js());
    }
}
