// =============================================================================
// WorkspaceRequest — what a user asks of the workspace, as data: generated by
// a control — a picker, a tab's cross, a menu — and executed by the core
// (WorkspaceCore.execute), in the order fixed for its type. A control never
// acts itself: it asks. The dual of WorkspaceCore.Request in Java.
//
//   WorkspaceRequest.open(kind, params, location) → { kind: "Open", widgetKind, params, location }
//                  a widget of a kind, with its params, opened and mounted at the location named —
//                  the placement's own word for where
//   WorkspaceRequest.close(id) → { kind: "Close", id }   a widget unmounted, then closed
// =============================================================================

class WorkspaceRequest {
    static open(kind, params, location) {
        if (typeof kind !== "string" || !kind) throw new Error("[WorkspaceRequest] an open names a kind");
        return Object.freeze({ kind: "Open", widgetKind: kind, params: Object.freeze(Object.assign({}, params || {})), location: location === undefined ? null : location });
    }

    static close(id) {
        if (typeof id !== "string" || !id) throw new Error("[WorkspaceRequest] a close names a widget");
        return Object.freeze({ kind: "Close", id: id });
    }
}
