package hue.captains.singapura.js.homing.workspace.monitors;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.widgets.WorkspaceManifest;

import java.util.List;

/**
 * The monitors' workspace as its page has it: {@code MONITORS_WORKSPACE},
 * generated from {@link MonitorsWorkspace} - its kinds, each its class and its
 * title; its root parties, none - so the page's workspace is Java's. A DOM
 * module, though it touches no DOM: it imports the widgets' classes (the
 * Keyboard's §15 hazard).
 */
public record MonitorsWorkspaceModule() implements DomModule<MonitorsWorkspaceModule>, SelfContent {

    public static final MonitorsWorkspaceModule INSTANCE = new MonitorsWorkspaceModule();

    public record MONITORS_WORKSPACE() implements Exportable._Constant<MonitorsWorkspaceModule> {}

    @Override public ImportsFor<MonitorsWorkspaceModule> imports() { return WorkspaceManifest.imports(MonitorsWorkspace.INSTANCE); }

    @Override
    public ExportsOf<MonitorsWorkspaceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new MONITORS_WORKSPACE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by MonitorsWorkspaceModule from MonitorsWorkspace - do not hand-edit: its kinds, and its root parties.",
                       WorkspaceManifest.js("MONITORS_WORKSPACE", MonitorsWorkspace.INSTANCE));
    }
}
