package hue.captains.singapura.js.homing.workspace.demo;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The demo's workspaces' first states in the split grid, as its page has them:
 * {@code DEMO_ARRANGEMENTS}, by kind, generated from {@link DemoArrangements}
 * through the site ({@code DemoGroups.SITE}).
 */
public record DemoArrangementsModule() implements EsModule<DemoArrangementsModule>, SelfContent {

    public static final DemoArrangementsModule INSTANCE = new DemoArrangementsModule();

    public record DEMO_ARRANGEMENTS() implements Exportable._Constant<DemoArrangementsModule> {}

    @Override public ImportsFor<DemoArrangementsModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DemoArrangementsModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_ARRANGEMENTS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoArrangementsModule from DemoGroups.SITE - do not hand-edit.",
                DemoGroups.SITE.arrangementsJs("DEMO_ARRANGEMENTS"));
    }
}
