package hue.captains.singapura.js.homing.workspace.demo;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.widgets.WorkspaceManifest;

import java.util.List;

/**
 * The demo workspace as its page has it: {@code DEMO_WORKSPACE}, generated
 * from {@link DemoWorkspace} - its kinds, each its class, its title and the
 * types it joins; its root parties, each its type and the secretary at its
 * root - so the page's workspace is Java's, and no second list can drift from
 * it. A DOM module, though it touches no DOM: it imports the widgets' classes
 * (the Keyboard's §15 hazard).
 */
public record DemoWorkspaceModule() implements DomModule<DemoWorkspaceModule>, SelfContent {

    public static final DemoWorkspaceModule INSTANCE = new DemoWorkspaceModule();

    public record DEMO_WORKSPACE() implements Exportable._Constant<DemoWorkspaceModule> {}

    @Override public ImportsFor<DemoWorkspaceModule> imports() { return WorkspaceManifest.imports(DemoWorkspace.INSTANCE); }

    @Override
    public ExportsOf<DemoWorkspaceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_WORKSPACE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoWorkspaceModule from DemoWorkspace - do not hand-edit: its kinds, and its root parties.",
                       WorkspaceManifest.js("DEMO_WORKSPACE", DemoWorkspace.INSTANCE));
    }
}
