package hue.captains.singapura.js.homing.workspace.demo;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The demo's workspaces as its page has them: {@code DEMO_WORKSPACES}, each
 * one's manifest by its kind, generated from their declarations - the kinds,
 * and the root parties. A DOM module, though it touches no DOM: it imports the
 * widgets' classes (WorkspaceManifest says why).
 */
public record DemoWorkspacesModule() implements DomModule<DemoWorkspacesModule>, SelfContent {

    public static final DemoWorkspacesModule INSTANCE = new DemoWorkspacesModule();

    public record DEMO_WORKSPACES() implements Exportable._Constant<DemoWorkspacesModule> {}

    @Override public ImportsFor<DemoWorkspacesModule> imports() { return DemoGroups.SITE.manifestsImports(); }

    @Override
    public ExportsOf<DemoWorkspacesModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_WORKSPACES())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoWorkspacesModule from DemoGroups.SITE - do not hand-edit: each workspace's kinds, and its root parties.",
                       DemoGroups.SITE.manifestsJs("DEMO_WORKSPACES"));
    }
}
