package hue.captains.singapura.js.homing.workspace.demo;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The demo's groups, as its page provides them to the directory:
 * {@code DEMO_GROUPS}, generated from {@link DemoGroups#GROUPS}.
 */
public record DemoGroupsModule() implements EsModule<DemoGroupsModule>, SelfContent {

    public static final DemoGroupsModule INSTANCE = new DemoGroupsModule();

    public record DEMO_GROUPS() implements Exportable._Constant<DemoGroupsModule> {}

    @Override public ImportsFor<DemoGroupsModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DemoGroupsModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DEMO_GROUPS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DemoGroupsModule from DemoGroups.GROUPS - do not hand-edit.",
                DemoGroups.SITE.groupsJs("DEMO_GROUPS"));
    }
}
