package hue.captains.singapura.js.homing.workspace.content;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The flow party's type, as the page has it: {@code FLOW}, generated from {@link FlowContent#TYPE} -
 * its name, and each kind's fields with their types - so every message is checked against what
 * Java declared.
 */
public record FlowContentModule() implements EsModule<FlowContentModule>, SelfContent {

    public static final FlowContentModule INSTANCE = new FlowContentModule();

    public record FLOW() implements Exportable._Constant<FlowContentModule> {}

    @Override public ImportsFor<FlowContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<FlowContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new FLOW())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by FlowContentModule from FlowContent.TYPE - do not hand-edit.", FlowContent.TYPE.js());
    }
}
