package hue.captains.singapura.js.homing.workspace.demowidgets.books;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The book selection party's type, as the page has it: {@code BOOK_SELECTION},
 * generated from {@link BookSelection#TYPE} - its name, and each kind's fields
 * with their types - so every message is checked against what Java declared.
 */
public record BookSelectionModule() implements EsModule<BookSelectionModule>, SelfContent {

    public static final BookSelectionModule INSTANCE = new BookSelectionModule();

    public record BOOK_SELECTION() implements Exportable._Constant<BookSelectionModule> {}

    @Override public ImportsFor<BookSelectionModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<BookSelectionModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new BOOK_SELECTION())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by BookSelectionModule from BookSelection.TYPE - do not hand-edit.", BookSelection.TYPE.js());
    }
}
