package hue.captains.singapura.js.homing.workspace.bench;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.workspace.parties.PartyType;
import hue.captains.singapura.js.homing.workspace.widgets.WidgetDeclaration;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The bench's kinds, as the page looks them up: {@code BENCH_WIDGETS[kind]} is
 * the class a kind constructs. Generated from {@link WidgetBench#KINDS}, each
 * class imported from the module that exports it, so the page's list is the
 * codec's, and no second list can drift from it. And the monitors, as the
 * bench's toggles float them: {@code BENCH_MONITORS}, each its kind, its title,
 * the mark on its toggle, and its class, from {@link WidgetBench#MONITORS}.
 *
 * <p>A {@code DomModule}, though it touches no DOM: a plain module's imports
 * are served without the page's theme, so the widget it imports - and the
 * parties and the steward the widget imports - would load a second time, a
 * second DomOpsParty and a second steward on one page (the Keyboard's §15
 * hazard). As a DOM module, its imports are the page's own.</p>
 */
public record BenchWidgetsModule() implements DomModule<BenchWidgetsModule>, SelfContent {

    public static final BenchWidgetsModule INSTANCE = new BenchWidgetsModule();

    public record BENCH_WIDGETS() implements Exportable._Constant<BenchWidgetsModule> {}

    public record BENCH_MONITORS() implements Exportable._Constant<BenchWidgetsModule> {}

    public record BENCH_PARTIES() implements Exportable._Constant<BenchWidgetsModule> {}

    @Override
    public ImportsFor<BenchWidgetsModule> imports() {
        var b = ImportsFor.<BenchWidgetsModule>builder();
        for (WidgetDeclaration<?> k : WidgetBench.KINDS) b.add(k.constructs());
        // each type a kind declares, as a page has it: its constant
        var constants = new LinkedHashSet<ModuleImports<?>>();
        for (WidgetDeclaration<?> k : WidgetBench.KINDS) for (PartyType<?> t : k.parties()) {
            constants.add(t.constant().orElseThrow(() -> new IllegalStateException(k.kind() + " joins " + t.name() + ", which is not served on a page")));
        }
        for (ModuleImports<?> c : constants) b.add(c);
        return b.build();
    }

    @Override
    public ExportsOf<BenchWidgetsModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new BENCH_WIDGETS(), new BENCH_MONITORS(), new BENCH_PARTIES())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        String entries = WidgetBench.KINDS.stream()
                .map(k -> "\"" + k.kind() + "\": " + k.className())
                .collect(Collectors.joining(", "));
        String monitors = WidgetBench.MONITORS.stream()
                .map(k -> "Object.freeze({ kind: \"" + k.kind() + "\", title: \"" + k.title() + "\", mark: \"" + k.title().substring(0, 1)
                        + "\", Widget: " + k.className() + " })")
                .collect(Collectors.joining(", "));
        String parties = WidgetBench.KINDS.stream()
                .map(k -> "\"" + k.kind() + "\": Object.freeze([" + k.parties().stream().map(PartyType::constName).collect(Collectors.joining(", ")) + "])")
                .collect(Collectors.joining(", "));
        return List.of(
                "// Generated by BenchWidgetsModule from WidgetBench.KINDS - do not hand-edit: the class each kind constructs.",
                "const BENCH_WIDGETS = Object.freeze({ " + entries + " });",
                "// Generated from WidgetBench.MONITORS: the monitors the bench's toggles float, in the bar's order.",
                "const BENCH_MONITORS = Object.freeze([" + monitors + "]);",
                "// Generated from each kind's declaration: the messaging parties' types a widget of it is given.",
                "const BENCH_PARTIES = Object.freeze({ " + parties + " });");
    }
}
