package hue.captains.singapura.js.homing.workspace.bench;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.widgets.WidgetDeclaration;

import java.util.List;
import java.util.stream.Collectors;

/**
 * The bench's kinds, as the page looks them up: {@code BENCH_WIDGETS[kind]} is
 * the class a kind constructs. Generated from {@link WidgetBench#KINDS}, each
 * class imported from the module that exports it, so the page's list is the
 * codec's, and no second list can drift from it.
 *
 * <p>A {@code DomModule}, though it touches no DOM: a plain module's imports
 * are served without the page's theme, so the widget it imports - and the
 * parties and the steward the widget imports - would load a second time, a
 * second DomOpsParty and a second steward on one page (the Keyboard's §15
 * hazard). As a DOM module, its imports are the page's own.</p>
 */
public record BenchWidgetsModule() implements DomModule<BenchWidgetsModule>, SelfContent {

    public static final BenchWidgetsModule INSTANCE = new BenchWidgetsModule();

    public record BENCH_WIDGETS() implements Exportable._Constant<BenchWidgetsModule> {}

    @Override
    public ImportsFor<BenchWidgetsModule> imports() {
        var b = ImportsFor.<BenchWidgetsModule>builder();
        for (WidgetDeclaration<?> k : WidgetBench.KINDS) b.add(k.constructs());
        return b.build();
    }

    @Override
    public ExportsOf<BenchWidgetsModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new BENCH_WIDGETS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        String entries = WidgetBench.KINDS.stream()
                .map(k -> "\"" + k.kind() + "\": " + k.className())
                .collect(Collectors.joining(", "));
        return List.of(
                "// Generated by BenchWidgetsModule from WidgetBench.KINDS - do not hand-edit: the class each kind constructs.",
                "const BENCH_WIDGETS = Object.freeze({ " + entries + " });");
    }
}
