package hue.captains.singapura.js.homing.workspace.demowidgets;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.workspace.widgets.WorkspaceManifest;

import java.util.List;

/**
 * The books workspace as its page has it: {@code BOOKS_WORKSPACE}, generated
 * from {@link BooksWorkspace} - its kinds, each its class, its title and the
 * types it joins; its root parties, each its type and the secretary at its
 * root - so the page's workspace is Java's, and no second list can drift from
 * it. A DOM module, though it touches no DOM: it imports the widgets' classes
 * (the Keyboard's §15 hazard).
 */
public record BooksWorkspaceModule() implements DomModule<BooksWorkspaceModule>, SelfContent {

    public static final BooksWorkspaceModule INSTANCE = new BooksWorkspaceModule();

    public record BOOKS_WORKSPACE() implements Exportable._Constant<BooksWorkspaceModule> {}

    @Override public ImportsFor<BooksWorkspaceModule> imports() { return WorkspaceManifest.imports(BooksWorkspace.INSTANCE); }

    @Override
    public ExportsOf<BooksWorkspaceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new BOOKS_WORKSPACE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by BooksWorkspaceModule from BooksWorkspace - do not hand-edit: its kinds, and its root parties.",
                       WorkspaceManifest.js("BOOKS_WORKSPACE", BooksWorkspace.INSTANCE));
    }
}
